# # -*- coding: utf-8 -*-
# """Untitled0.ipynb
#
# Automatically generated by Colaboratory.
#
# Original file is located at
#     https://colab.research.google.com/drive/1UBKbn6IWwsDz59UyZ6naj2UexLCvUHZH
# """
#
# pip install transformers
#
# from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer
#
# ARTICLE = """ New York (CNN)When Liana Barrientos was 23 years old, she got married in Westchester County, New York.
# A year later, she got married again in Westchester County, but to a different man and without divorcing her first husband.
# Only 18 days after that marriage, she got hitched yet again. Then, Barrientos declared "I do" five more times, sometimes only within two weeks of each other.
# In 2010, she married once more, this time in the Bronx. In an application for a marriage license, she stated it was her "first and only" marriage.
# Barrientos, now 39, is facing two criminal counts of "offering a false instrument for filing in the first degree," referring to her false statements on the
# 2010 marriage license application, according to court documents.
# Prosecutors said the marriages were part of an immigration scam.
# On Friday, she pleaded not guilty at State Supreme Court in the Bronx, according to her attorney, Christopher Wright, who declined to comment further.
# After leaving court, Barrientos was arrested and charged with theft of service and criminal trespass for allegedly sneaking into the New York subway through an emergency exit, said Detective
# Annette Markowski, a police spokeswoman. In total, Barrientos has been married 10 times, with nine of her marriages occurring between 1999 and 2002.
# All occurred either in Westchester County, Long Island, New Jersey or the Bronx. She is believed to still be married to four men, and at one time, she was married to eight men at once, prosecutors say.
# Prosecutors said the immigration scam involved some of her husbands, who filed for permanent residence status shortly after the marriages.
# Any divorces happened only after such filings were approved. It was unclear whether any of the men will be prosecuted.
# The case was referred to the Bronx District Attorney\'s Office by Immigration and Customs Enforcement and the Department of Homeland Security\'s
# Investigation Division. Seven of the men are from so-called "red-flagged" countries, including Egypt, Turkey, Georgia, Pakistan and Mali.
# Her eighth husband, Rashid Rajput, was deported in 2006 to his native Pakistan after an investigation by the Joint Terrorism Task Force.
# If convicted, Barrientos faces up to four years in prison.  Her next court appearance is scheduled for May 18.
# """
#
# model = TFAutoModelForSeq2SeqLM.from_pretrained("t5-base")
# tokenizer = AutoTokenizer.from_pretrained("t5-base")
#
# # T5 uses a max_length of 512 so we cut the article to 512 tokens.
# inputs = tokenizer("summarize: " + ARTICLE, return_tensors="tf", max_length=512)
# outputs = model.generate(
#     inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True
# )
#
# print(tokenizer.decode(outputs[0], skip_special_tokens=True))
#
# # print(tokenizer.decode(outputs[0], skip_special_tokens=True))
#
# # pip install SentencePiece
# #
# # pip install tensorflow
# #
# # pip install sentencepiece
# #
# # pip install torch
# #
# # from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
# #
# # tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-sw")
# #
# # model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-sw")
# #
# # inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
# #
# # last_hidden_states = outputs.last_hidden_state
# #
# # # test = type(inputs)
# #
# # # test
# # # outputs = model(inputs)
# #
# # from transformers import MarianTokenizer, TFMarianMTModel
# # from typing import List
# #
# # src = "en"  # source language
# # trg = "sw"  # target language
# # sample_text = "where is the bus now ?"
# # model_name = f"Helsinki-NLP/opus-mt-{src}-{trg}"
# #
# # model = TFMarianMTModel.from_pretrained(model_name)
# # tokenizer = MarianTokenizer.from_pretrained(model_name)
# # batch = tokenizer([sample_text], return_tensors="tf")
# # gen = model.generate(**batch)
# # tokenizer.batch_decode(gen, skip_special_tokens=True)
# #
# # tokenizer.batch_decode(gen, skip_special_tokens=True)
#
# from flask import Flask, render_template, request
#
# # import pandas as pd
# # import joblib
#
# # load our model
# # model = joblib.load("Type of Food")
#
# # make our Flask api...
# app = Flask(__name__, template_folder="template")
#
#
# # form urls/...
# @app.route("/")
# def home():
#     return render_template("Type.html")
#
#
# @app.route("/prediction", methods=["POST"])
# def prediction():
#     # # Accepting form data
#     modelName = request.form["modelName"]
#     testDocument = request.form["textArea"]
#     # # print(modelName)
#     # # print(testDocument)
#     # # exit()
#     if modelName == "Summarize":
#
#         # # creating an out of sample data/question using dictionary
#         # damp = {"textArea1": q, "textArea": w}
#         #
#         # # converting the dictionary into Pandas dataframe
#         # test = pd.DataFrame(damp, index=[289])
#
#         # # parsing it to our model for predicting
#         # result = model.predict(test)
#         # results = result
#
#         # from transformers import pipeline
#         #
#         # # Importing methods from summarization Pipeline.
#         # textSummerizer = pipeline("summarization")
#         #
#         # # Configuring the summarizer
#         # result = textSummerizer(testDocument, maxLength=130, minLength=30, do_sample=False)
#         # # result = testDocument
#         # #     # return prediction.
#         from transformers import TFAutoModelForSeq2SeqLM, AutoTokenizer, PreTrainedTokenizerBase
#
#         model = TFAutoModelForSeq2SeqLM.from_pretrained("t5-base")
#         tokenizer = AutoTokenizer.from_pretrained("t5-base")
#
#         # T5 uses a max_length of 512 so we cut the article to 512 tokens.
#         inputs = tokenizer("summarize: " + testDocument, return_tensors="tf", max_length=512)
#         outputs = model.generate(
#             inputs["input_ids"], max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True
#         )
#
#         result = tokenizer.decode(outputs[0], skip_special_tokens=True)
#
#         return render_template("Type1.html", pred="The summarized text is : {}".format(
#             result))
#     else:
#
#         from transformers import MarianTokenizer, TFMarianMTModel, PreTrainedTokenizerBase
#         src = "en"  # source language
#         trg = "sw"  # target language
#         model_name = f"Helsinki-NLP/opus-mt-{src}-{trg}"
#
#         model = TFMarianMTModel.from_pretrained(model_name)
#         tokenizer: PreTrainedTokenizerBase = MarianTokenizer.from_pretrained(model_name)
#         batch = tokenizer([testDocument], return_tensors="tf")
#         gen = model.generate(**batch)
#         result = tokenizer.batch_decode(gen, skip_special_tokens=True)
#         # result = testDocument
#         return render_template("Type1.html", pred="The Translated text is : {}".format(
#             result))
#
#
# # Run this file as the main file...
# if __name__ == "__main__":
#     app.run(debug=True)
